PROCESS BEFORE OUTPUT.
 MODULE STATUS_9900.
   LOOP WITH CONTROL flights.
    MODULE module_fill_table.
  ENDLOOP.

  CALL SUBSCREEN sub INCLUDING sy-repid number.

PROCESS AFTER INPUT.
  CALL SUBSCREEN sub.

  LOOP WITH CONTROL FLIGHTS.
    MODULE module_read_table.
  ENDLOOP.

 MODULE USER_COMMAND_9900.
