CLASS zbp_r_rootentity95 DEFINITION
  PUBLIC
  FOR BEHAVIOR OF zr_rootentity95 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_r_rootentity95 IMPLEMENTATION.
ENDCLASS.
