CLASS zcl_demo_abap_evt_handler96 DEFINITION
  PUBLIC ABSTRACT FINAL
  FOR EVENTS OF ZR_DEMO_ABAP96.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_demo_abap_evt_handler96 IMPLEMENTATION.
ENDCLASS.
